---
- name: "Updating CDNSITEs with their assigned sites"
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: adding site to cdnsites 
      networktocode.nautobot.plugin:
        url: "{{ dev_nb_url }}"
        token: "{{ dev_nb_token }}"
        plugin: nautobot-cdn-models
        endpoint: cdnsite
        validate_certs: false
        identifiers:
          name: "beta_Carolinas_Charlotte_NC_linear_hpc"
        attrs:
          cacheMemoryProfileId:
            name: Linear-HPC-FEC
          site:
            slug: albynyyf
          # neighbor1:
          #   name: beta_Carolinas_NCEast_NC_linear_shield
          # neighbor1_preference: 600
          # neighbor2:
          #   name: beta_NorthWest_NCWest_CO_linear_shield
          # neighbor2_preference: 500