prod_regions:
  - name: Carolinas
    slug: carolinas
  - name: Central
    slug: central
  - name: COLOCATION
    slug: colocation
  - name: Florida
    slug: florida
  - name: Great Lakes
    slug: great-lakes
  - name: National Datacenter East
    slug: national-datacenter-east
  - name: National Datacenter West
    slug: national-datacenter-west
  - name: New York City
    slug: new-york-city
  - name: Northeast
    slug: northeast
  - name: Northwest
    slug: northwest
  - name: RDC
    slug: rdc
  - name: South
    slug: south
  - name: Ohio
    slug: southern-ohio
  - name: Texas
    slug: texas
  - name: West
    slug: west
