# Generated by Django 3.2.20 on 2023-07-14 19:12

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields
import nautobot.extras.models.mixins
import nautobot.extras.utils
import nautobot_cdn_models.models.contexts
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0019_device_redundancy_group_data_migration'),
        ('extras', '0053_relationship_required_on'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('nautobot_cdn_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnConfigContextSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=200, populate_from='name', unique=None)),
                ('data_schema', models.JSONField()),
                ('owner_object_id', models.UUIDField(blank=True, default=None, null=True)),
                ('owner_content_type', models.ForeignKey(blank=True, default=None, limit_choices_to=nautobot.extras.utils.FeatureQuery('config_context_owners'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='CdnConfigContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('owner_object_id', models.UUIDField(blank=True, default=None, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=1000)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('cdn_site_roles', models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_cdn_site_roles_+', to='dcim.DeviceRole')),
                ('cdnsites', models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_cdnsites_+', to='dcim.Site')),
                ('locations', models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_locations_+', to='dcim.Location')),
                ('owner_content_type', models.ForeignKey(blank=True, default=None, limit_choices_to=nautobot.extras.utils.FeatureQuery('config_context_owners'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('regions', models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_regions_+', to='dcim.Region')),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extras.configcontextschema')),
                ('tags', models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_tags_+', to='extras.Tag')),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='cdnconfigcontextschema',
            constraint=models.UniqueConstraint(fields=('name', 'owner_content_type', 'owner_object_id'), name='cdn_unique_name_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='cdnconfigcontext',
            unique_together={('name', 'owner_content_type', 'owner_object_id')},
        ),
    ]
