# Generated by Django 3.2.22 on 2023-11-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CdnGitRepository',
        ),
    ]
