# Generated by Django 3.2.20 on 2023-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0002_auto_20230714_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdnconfigcontext',
            name='cdn_site_roles',
            field=models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_cdn_site_roles_+', to='nautobot_cdn_models.SiteRole'),
        ),
        migrations.AlterField(
            model_name='cdnconfigcontext',
            name='cdnsites',
            field=models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_cdnsites_+', to='nautobot_cdn_models.CdnSite'),
        ),
    ]
