# Generated by Django 3.2.20 on 2023-07-27 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0003_auto_20230714_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdnsite',
            name='neighbor2_preference',
            field=models.IntegerField(blank=True, default=750, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
