# Generated by Django 3.2.20 on 2023-08-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0019_device_redundancy_group_data_migration'),
        ('nautobot_cdn_models', '0006_remove_cdnsite_failover_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnsite',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdnsites', to='dcim.site'),
        ),
    ]
