# Generated by Django 3.2.20 on 2023-09-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0007_cdnsite_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CdnConfigContextSchema',
        ),
    ]
