# Generated by Django 3.2.20 on 2023-09-05 14:54

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields
import nautobot.extras.models.mixins
import nautobot.extras.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nautobot_cdn_models', '0008_delete_cdnconfigcontextschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnConfigContextSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=200, populate_from='name', unique=None)),
                ('data_schema', models.JSONField()),
                ('owner_object_id', models.UUIDField(blank=True, default=None, null=True)),
                ('owner_content_type', models.ForeignKey(blank=True, default=None, limit_choices_to=nautobot.extras.utils.FeatureQuery('config_context_owners'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.AddConstraint(
            model_name='cdnconfigcontextschema',
            constraint=models.UniqueConstraint(fields=('name', 'owner_content_type', 'owner_object_id'), name='cdn_unique_name_owner'),
        ),
    ]
