# Generated by Django 3.2.20 on 2023-11-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0009_auto_20230905_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnsite',
            name='failover_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sister_site', to='nautobot_cdn_models.cdnsite'),
        ),
    ]
