# Generated by Django 3.2.20 on 2023-11-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0010_cdnsite_failover_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnconfigcontext',
            name='failover_site',
            field=models.ManyToManyField(blank=True, related_name='_nautobot_cdn_models_cdnconfigcontext_failover_site_+', to='nautobot_cdn_models.CdnSite'),
        ),
    ]
