# Generated by Django 3.2.20 on 2023-11-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0012_auto_20231121_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentprovider',
            old_name='account',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='account',
            new_name='slug',
        ),
    ]
