# Generated by Django 3.2.23 on 2023-11-22 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0014_auto_20231122_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='cacheableErrorResponseCodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=10), blank=True, default=list, size=10),
        ),
        migrations.AlterField(
            model_name='origin',
            name='resolvableHostnames',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), blank=True, size=8),
        ),
    ]
