# Generated by Django 3.2.23 on 2023-11-25 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0018_alter_cdnsite_hypercachememoryprofileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypercachememoryprofile',
            name='cacheMemoryProfileId',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
