# Generated by Django 3.2.23 on 2023-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0019_alter_hypercachememoryprofile_cachememoryprofileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypercachememoryprofile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
