# Generated by Django 3.2.23 on 2023-11-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0020_alter_hypercachememoryprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hypercachememoryprofile',
            options={'ordering': ['name']},
        ),
    ]
