# Generated by Django 3.2.23 on 2023-11-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0021_alter_hypercachememoryprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdnsite',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
