# Generated by Django 3.2.23 on 2023-11-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_cdn_models', '0022_alter_cdnsite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdnsite',
            name='hyperCacheMemoryProfileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdnsites', to='nautobot_cdn_models.hypercachememoryprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='cdnsite',
            unique_together={('cdn_site_role', 'name')},
        ),
    ]
