changed: false
data:
    tenants:
    -   cf_cache_memory_profile_id: null
        cf_cache_memory_profile_name: ''
        cf_clli_code: ''
        cf_diskless_mode: false
        cf_neighbor_1: ''
        cf_neighbor_2: ''
        cf_site_id: 1
        cpf_site_abbreviated_name: ''
        devices:
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 5104a39e-d091-4fdf-a6ba-9a78046b4426
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e2::4/64
                -   address: 98.8.59.212/28
                name: eth0
            name: chrcnctr01-ecdn-rtr0001.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Request Router
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: d18f74c5-c729-4e8c-bb20-3a06eb4636f6
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e2::5/64
                -   address: 98.8.59.213/28
                name: eth0
            name: chrcnctr01-ecdn-rtr0002.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Request Router
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 6262bd37-f6a6-49b6-9ec4-f12d8f7bbf5f
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e2::4/64
                -   address: 98.8.61.180/28
                name: eth0
            name: enwdcocd02-ecdn-rtr0001.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Request Router
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 8a3a50c4-1550-4279-8b90-61d3364bee9a
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e2::5/64
                -   address: 98.8.61.181/28
                name: eth0
            name: enwdcocd02-ecdn-rtr0002.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Request Router
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control
        group:
            id: b7540c26-bac1-4f5c-8355-ecdfa76933a6
            name: Spectrum Enterprise Control Plane
        id: 76c1676b-1324-47ac-9333-c944934271fc
        name: enterprise_cdn_control
    -   cf_cache_memory_profile_id: null
        cf_cache_memory_profile_name: ''
        cf_clli_code: ''
        cf_diskless_mode: false
        cf_neighbor_1: ''
        cf_neighbor_2: ''
        cf_site_id: 3
        cpf_site_abbreviated_name: ''
        devices:
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 0fc9958e-e232-4ab0-8cb7-bbd0629b7dea
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e0::5/64
                -   address: 98.8.59.86/28
                name: eth0
            name: chrcnctr01-ecdn-aas0001.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Analytics
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control_aas
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: b5d90b73-4201-4dd2-bc5f-4cd69c30ad0d
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e0::6/64
                -   address: 98.8.59.87/28
                name: eth0
            name: chrcnctr01-ecdn-aas0002.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Analytics
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control_aas
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 0e55e113-fd68-41a9-b11f-4042abd17404
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e0::7/64
                -   address: 98.8.59.88/28
                name: eth0
            name: chrcnctr01-ecdn-aas0003.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Analytics
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control_aas
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 038f29fd-1835-493a-b637-a11c1e1f0c99
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e0::5/64
                -   address: 98.8.61.54/28
                name: eth0
            name: enwdcocd02-ecdn-aas0001.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Analytics
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control_aas
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 2328be75-983a-4aef-91f4-881956106f88
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e0::6/64
                -   address: 98.8.61.55/28
                name: eth0
            name: enwdcocd02-ecdn-aas0002.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Analytics
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control_aas
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context: {}
            id: 1e9327dd-c17f-42b8-b722-8f72c728f743
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e0::7/64
                -   address: 98.8.61.56/28
                name: eth0
            name: enwdcocd02-ecdn-aas0003.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Analytics
            status:
                name: Planned
            tenant:
                name: enterprise_cdn_control_aas
        group:
            id: b7540c26-bac1-4f5c-8355-ecdfa76933a6
            name: Spectrum Enterprise Control Plane
        id: 86d8b300-5edf-49a2-8a7f-915cc3c030c9
        name: enterprise_cdn_control_aas
    -   cf_cache_memory_profile_id: 1274
        cf_cache_memory_profile_name: Linear-Shield
        cf_clli_code: chrcnctr01
        cf_diskless_mode: true
        cf_neighbor_1: spectrum_enterprise_ecdn_ndcwest_linear_shield
        cf_neighbor_2: ''
        cf_site_id: 4
        cpf_site_abbreviated_name: chrcnctr01_l_shc
        devices:
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context:
                cachingmemoryoverridemb: 51200
                clientservingbwlimitmbps: 9000
            id: c7de83ce-fa0b-4931-a2c1-30448e593d3b
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e1::4/64
                -   address: 98.8.59.196/28
                name: eth0
            name: chrcnctr01-ecdn-shc1001.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Shield Cache
            status:
                name: Planned
            tenant:
                name: spectrum_enterprise_ecdn_ndceast_linear_shield
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context:
                cachingmemoryoverridemb: 51200
                clientservingbwlimitmbps: 9000
            id: 9a31978e-7015-4b94-a25f-3de7ad56c9f9
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e1::5/64
                -   address: 98.8.59.197/28
                name: eth0
            name: chrcnctr01-ecdn-shc1002.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Shield Cache
            status:
                name: Planned
            tenant:
                name: spectrum_enterprise_ecdn_ndceast_linear_shield
        -   _custom_field_data: {}
            cluster:
                name: Charlotte Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context:
                cachingmemoryoverridemb: 51200
                clientservingbwlimitmbps: 9000
            id: 88437b2b-52e0-4ca3-8f9d-759b48218c30
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9330:e1::6/64
                -   address: 98.8.59.198/28
                name: eth0
            name: chrcnctr01-ecdn-shc1003.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Shield Cache
            status:
                name: Planned
            tenant:
                name: spectrum_enterprise_ecdn_ndceast_linear_shield
        group:
            id: 5bbcb13e-287c-4194-bbd4-151c1471de54
            name: Spectrum Enterprise HPCs
        id: 13963659-52d2-4bca-be0c-094d3dd2af03
        name: spectrum_enterprise_ecdn_ndceast_linear_shield
    -   cf_cache_memory_profile_id: 1274
        cf_cache_memory_profile_name: Linear-Shield
        cf_clli_code: enwdcocd02
        cf_diskless_mode: true
        cf_neighbor_1: spectrum_enterprise_ecdn_ndceast_linear_shield
        cf_neighbor_2: ''
        cf_site_id: 5
        cpf_site_abbreviated_name: enwdcocd02_l_shc
        devices:
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context:
                cachingmemoryoverridemb: 51200
                clientservingbwlimitmbps: 9000
            id: af941b28-1739-4d24-b110-21df92ca5c23
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e1::4/64
                -   address: 98.8.61.164/28
                name: eth0
            name: enwdcocd02-ecdn-shc1001.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Shield Cache
            status:
                name: Planned
            tenant:
                name: spectrum_enterprise_ecdn_ndcwest_linear_shield
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context:
                cachingmemoryoverridemb: 51200
                clientservingbwlimitmbps: 9000
            id: 83ff10a8-a395-49f9-a718-f7a895a4fe15
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e1::5/64
                -   address: 98.8.61.165/28
                name: eth0
            name: enwdcocd02-ecdn-shc1002.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Shield Cache
            status:
                name: Planned
            tenant:
                name: spectrum_enterprise_ecdn_ndcwest_linear_shield
        -   _custom_field_data: {}
            cluster:
                name: Peakview Spectrum Enterprise eCDN
                type:
                    name: ecdn
            config_context:
                cachingmemoryoverridemb: 51200
                clientservingbwlimitmbps: 9000
            id: 6f0a01ee-4036-48f8-8594-2c83a1d859b5
            interfaces:
            -   ip_addresses:
                -   address: 2600:6c7f:9340:e1::6/64
                -   address: 98.8.61.166/28
                name: eth0
            name: enwdcocd02-ecdn-shc1003.spectrum.com
            role:
                name: Spectrum Enterprise eCDN Shield Cache
            status:
                name: Planned
            tenant:
                name: spectrum_enterprise_ecdn_ndcwest_linear_shield
        group:
            id: 5bbcb13e-287c-4194-bbd4-151c1471de54
            name: Spectrum Enterprise HPCs
        id: 4549033f-654c-4cb7-b3f9-dc30320c6712
        name: spectrum_enterprise_ecdn_ndcwest_linear_shield
failed: false
graph_variables: null
query: "{\ntenants(name__ic: \"enterprise\") {\n  name\n  id\n  group {\n    name\n\
    \    id\n  }\n    cf_cache_memory_profile_id\n    cf_cache_memory_profile_name\n\
    \    cf_clli_code\n    cf_diskless_mode\n    cf_neighbor_1\n    cf_neighbor_2\n\
    \    cf_site_id\n    cpf_site_abbreviated_name\n    devices: virtual_machines\
    \ {\n      name\n      id\n      cluster {\n        name\n        type {\n   \
    \       name\n        }\n      }\n      _custom_field_data\n      status {\n \
    \     name\n      }\n      role {\n        name\n      }\n      tenant {\n   \
    \     name\n      }\n      interfaces {\n        name\n        ip_addresses {\n\
    \          address\n        }\n      }\n      config_context\n    }\n  }\n}\n"
url: https://pvdcco-ch-utl-1002.spectrum.com/
