sites:
  - name: centennial_enwdcocd
    physical_address: 11011 EAST PEAKVIEW AVE CENTENNIAL CO 80111
  - name: centennial_enwdcocd
    physical_address: 11011 EAST PEAKVIEW AVE CENTENNIAL CO 80111
  - name: centennial_enwdcocd
    physical_address: 11011 EAST PEAKVIEW AVE CENTENNIAL CO 80111
  - name: charlotte_chrcnctr
    physical_address: 8730 GREEN RIDGE DRIVE CHARLOTTE NC 28217
  - name: charlotte_chrcnctr
    physical_address: 8730 GREEN RIDGE DRIVE CHARLOTTE NC 28217
  - name: charlotte_chrcnctr
    physical_address: 8730 GREEN RIDGE DRIVE CHARLOTTE NC 28217
roles:
  - name: Enterprise Akamai LCDN
  - name: Enterprise Akamai LCDN
  - name: Enterprise Akamai LCDN
  - name: Enterprise Akamai LCDN
  - name: Enterprise Akamai LCDN
  - name: Enterprise Akamai LCDN
vlans:
  - name: SPECTRUM_ENT_AKAMAI_CONTROL_PLANE
    vid: 260
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
  - name: SPECTRUM_ENT_AKAMAI_SC_FRONT
    vid: 261
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
  - name: SPECTRUM_ENT_AKAMAI_RR
    vid: 263
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
  - name: SPECTRUM_ENT_AKAMAI_CONTROL_PLANE
    vid: 260
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
  - name: SPECTRUM_ENT_AKAMAI_SC_FRONT
    vid: 261
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
  - name: SPECTRUM_ENT_AKAMAI_RR
    vid: 263
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
prefixes:
  - prefix: 2600:6c7f:9340:e0::/64
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
    vlan: SPECTRUM_ENT_AKAMAI_CONTROL_PLANE
  - prefix: 98.8.61.48/28
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
    vlan: SPECTRUM_ENT_AKAMAI_CONTROL_PLANE
  - prefix: 2600:6c7f:9340:e1::/64
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
    vlan: SPECTRUM_ENT_AKAMAI_SC_FRONT
  - prefix: 98.8.61.160/28
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
    vlan: SPECTRUM_ENT_AKAMAI_SC_FRONT
  - prefix: 2600:6c7f:9340:e2::/64
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
    vlan: SPECTRUM_ENT_AKAMAI_RR
  - prefix: 98.8.61.176/28
    role: Enterprise Akamai LCDN
    site: centennial_enwdcocd
    vlan: SPECTRUM_ENT_AKAMAI_RR
  - prefix: 2600:6c7f:9330:e0::/64
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
    vlan: SPECTRUM_ENT_AKAMAI_CONTROL_PLANE
  - prefix: 98.8.59.80/28
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
    vlan: SPECTRUM_ENT_AKAMAI_CONTROL_PLANE
  - prefix: 2600:6c7f:9330:e1::/64
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
    vlan: SPECTRUM_ENT_AKAMAI_SC_FRONT
  - prefix: 98.8.59.192/28
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
    vlan: SPECTRUM_ENT_AKAMAI_SC_FRONT
  - prefix: 2600:6c7f:9330:e2::/64
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
    vlan: SPECTRUM_ENT_AKAMAI_RR
  - prefix: 98.8.59.208/28
    role: Enterprise Akamai LCDN
    site: charlotte_chrcnctr
    vlan: SPECTRUM_ENT_AKAMAI_RR
