---
- name: Get Relationships IDs for Devices
  uri: 
    url: "http://127.0.0.1:8080/api/extras/relationships/?name=CdnSite%27s%20Associated%20Devices"
    method: GET
    return_content: yes
    status_code: "200"
    validate_certs: false
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ dev_nb_token }}"
  register: device_rel_id

- name: Get CDNSITE ID for {{ item.tenant }}
  networktocode.nautobot.query_graphql:
    url: "{{ dev_nb_url }}"
    token: "{{ dev_nb_token }}"
    validate_certs: False
    query: |
      {
        cdn_sites (name: "{{ item.tenant }}"){
          name
          id
        }
      }
  register: cdnsite_id

- name: Get Device ID for {{ item.name }}
  networktocode.nautobot.query_graphql:
    url: "{{ dev_nb_url }}"
    token: "{{ dev_nb_token }}"
    validate_certs: False
    query: |
      {
        devices (name: "{{ item.name }}"){
          name
          id
        }
      }
  register: device_id


- name: Associate devices to CDN Sites
  networktocode.nautobot.relationship_association:
    url: "{{ dev_nb_url }}"
    token: "{{ dev_nb_token }}"
    validate_certs: no
    relationship: "{{ device_rel_id.json.id }}"
    source_type: dcim.device
    source_id: "{{ device_id.data.devices.0.id }}"
    destination_type: nautobot_cdn_models.cdnsite
    destination_id: "{{ cdnsite_id.data.cdn_sites.0.id }}"